### PR TITLE
feat: wireless monitor

### PR DESCRIPTION
**Pull request by reinzor**
Monitors a given wireless interface using `psutil` and `iwconfig`. Follow up of https://github.com/ros-drivers/linux_peripheral_interfaces/pull/8#issuecomment-554608677

### CODE REVIEW

**Comment by k-okada** [comment]
Thanks, so should we Close #8 and use this one? Please set version 0.2.1 for your package.xml

**Comment by reinzor** [comment]
I guess so. Regarding the version bump, I think this should always be up to the maintainer who makes the release with the required `catkin` release tools: `catkin_generate_changelog`, `catkin_prepare_release` and `bloom-release`.

**Comment by k-okada** [comment]
Ok, before that , please add ‘wireless-tools` rosdep keys, os use available key. https://travis-ci.com/ros-drivers/linux_peripheral_interfaces/builds/136987617

```
  - wireless-tools
1724Traceback (most recent call last):
1725  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 271, in resolve_names
1726    rosdep_key, view, installer, os_name, os_code_name)
1727  File "/usr/lib/python3/dist-packages/rosdep2/catkin_support.py", line 87, in resolve_for_os
1728    d = view.lookup(rosdep_key)
1729  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 197, in lookup
1730    return self.rosdep_defs[rosdep_name]
1731KeyError: 'wireless-tools'
1732
1733During handling of the above exception, another exception occurred:
1734
1735Traceback (most recent call last):
1736  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 287, in <module>
1737    main()
1738  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 144, in main
1739    run_and_test_depends, **context)
1740  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 274, in resolve_names
1741    "Could not resolve the rosdep key '%s'" % rosdep_key)
1742RuntimeError: Could not resolve the rosdep key 'wireless-tools'
1743The command "cd $JOB_PATH; sh ./prerelease.sh -y" failed and exited with 1 during .
1744
1745Your build has been stopped.
```

**Comment by reinzor** [comment]
ping! https://github.com/ros/rosdistro/pull/23060 is merged

**Comment by reinzor** [comment]
There seems to be interest in this. Any time to look at this PR? Otherwise I will close it due to inactivity.

**Comment by reinzor** [comment]
Nobody seems to care, closing PR

**Comment by 130s** [comment]
@reinzor  @furushchev nice work!
I'm just not sure if wifi capability is worth a new package (I'm afraid doing so would raise the level of maintenance burden).

Without knowing this PR, I opened https://github.com/ros-drivers/linux_peripheral_interfaces/pull/20 to add a pkg to cover functionalities for non-sensor, computer hardware (as there's already a pkg for sensors on this repo). If it makes sense, I'm interested in adding your work into the new package I'm suggesting to add.

(Since https://github.com/ros-drivers/linux_peripheral_interfaces/pull/20 is supposed to be a generalized copy of the package that has existed somewhere else, I want to keep https://github.com/ros-drivers/linux_peripheral_interfaces/pull/20 as is. I can add the wifi stuff in another PR).

**Comment by reinzor** [comment]
Thanks @130s , I don't think this package is actively maintained anymore but you can try to ping the maintainers. Would be nice to see this merged.

**Pull request closed without merging**
