### PR TITLE
convert to sensor_msgs/BatteryState

### PR DESCRIPTION
**Pull request by tfoote**
We've standardized a [new sensor_msgs/BatteryState](http://docs.ros.org/api/sensor_msgs/html/msg/BatteryState.html) this will switch to use it. I'd recommend releasing this into Kinetic but not backporting to indigo and jade.

### CODE REVIEW

**Comment by tfoote** [comment]
After merging this a kinetic release would be great to get the TurtleBot stacks going.

**Comment by stonier** [comment]
We should probably push this into a kinetic branch to avoid accidental releases and disturbing anyone who is using the sources on indigo with an api change.

**Comment by stonier** [comment]
@jihoonl do you still want to maintain this or would you like me to pick  it up?

**Comment by jihoonl** [comment]
I can merge and releasing work. But other than that, it would be great if you can pick it up.

**Comment by jihoonl** [comment]
I couldn't do any extra activities so far because I don't have internet in home yet. :cry:

**Comment by stonier** [comment]
Created a `kinetic` branch and merged this pull request with changelog and package version bump (minor) there.

**Pull request closed without merging**
