### PR TITLE
Cleaned up libsensors diagnostics output

### PR DESCRIPTION
**Pull request by mitchellwills**
Made units consistent with laptop_battery_monitor
Use libsensors label as diagnostics label instead of name

### CODE REVIEW

**Comment by mitchellwills** [comment]
Hey @jihoonl any thoughts on this

**Comment by jihoonl** [comment]
@mitchellwills Do you have any sample output?

**Comment by mitchellwills** [comment]
Here's the output in rqt_robot_monitor
I also updated it so that there is no degree symbol cause it causes issues in some places
libsensors_monitor

**Comment by jihoonl** [comment]
:+1: Thanks.

**Pull request merged**
